alovajs/alova

- src/functions/createRequestState.ts
- src/predefine/ReactHook.ts
- test/browser/hooks/useRequest-react.spec.tsx
- typings/index.d.ts
feat(react): optimize the handlers of use hooks in react with `useCallback`
and now, you can use send and abort directly in events, and don't worry about the performance in react
fix #141
> release: v2.9.0

- src/functions/createRequestState.ts
- test/browser/hooks/vue/useRequest-http.spec.ts
- test/browser/middleware/useRequest.spec.ts
- typings/index.d.ts
Fixing type annotations and adding an optional chaining (?.) operator. (close #314)
> fix: use abort() before request sent cause an exception when using useRequest (#314)

- package.json
Link: [#361](https://github.com/alovajs/alova/issues/361#issuecomment-2111911445)
> fix(package.json): fix the path of require export

- .github/DISCUSSION_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/config.yml
- 添加了 Feature Request 的 Discussion Form
- 修改了 Issue 配置，现在可以直接在 Issue 中点击并跳转到新建 Feature Request 页面。
已在其他 Repo 测试其功能，it works ✅
**屏幕截图 / Screenshots**
> update: discussion form tamplate

- src/functions/createRequestState.ts
- src/functions/useHookToSendRequest.ts
- src/hooks/useRequest.ts
- src/hooks/useWatcher.ts
- src/utils/createAlovaEvent.ts
- src/utils/helper.ts
- typings/index.d.ts
> add generics `ARG` to fix the type error

- src/functions/sendRequest.ts
- test/browser/hooks/vue/useRequest-method.spec.ts
#382 
Fix: url was added with a slash when it was empty
**文档 / Docs**
When the url is empty, a slash is no longer added before it
> fix: remove slash at the end when sending with empty url

- .changeset/olive-apricots-deny.md
- .changeset/plenty-apricots-dress.md
- .changeset/plenty-dryers-sell.md
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/shared/build.json
- packages/shared/package.json
- packages/shared/tsconfig.json
- scripts/src/build/rollup.config.js
#404 
fix: cannot import from alova in react
> fix: cannot import from alova in react (#404)

- .changeset/shiny-pigs-pretend.md
- .changeset/thin-zebras-return.md
- internal/jest.setup.mock.ts
- packages/adapter-mock/src/MockRequest.ts
- packages/adapter-mock/test/mockRequest.spec.ts
- packages/adapter-mock/typings/index.d.ts
- packages/alova/typings/index.d.ts
- packages/client/src/hooks/core/implements/createRequestState.ts
- packages/client/src/hooks/silent/globalVariables.ts
- packages/client/src/hooks/silent/useSQRequest.ts
- packages/client/test/vue/useSQRequest.spec.ts
- packages/shared/src/function.ts
[Issue ID]
fix some beta bugs.
close #422, #424, #426, #427
**文档 / Docs**
tests have been added.
passed
> fix: return response data in `middleware.next` of `useSQRequest`

- src/functions/sendRequest.ts
- test/browser/hooks/react/useRequest.spec.tsx
close #449 
fix: cannot force send in restore mode in hooks
**文档 / Docs**
相关代码：[src/functions/sendRequest.ts#L121](https://github.com/alovajs/alova/blob/cdd0fb4ef9ff71e8d5ee5f65f0e4c065e4ec11c4/src/functions/sendRequest.ts#L121)
强制请求时，cache 不会被读取，因此为 `undefined`
如上述代码所示，在 restore 模式下只要 cache 为空，就尝试从持久化数据中恢复 cache。
这导致命中 cache ，认为本次请求无需发出。
PR 添加了判断条件，在 `force == true` 时始终不从持久化中恢复；并添加了一个针对 restore 和 force 请求的测试。
> fix: cannot force send in restore mode in hooks

- .changeset/angry-laws-dream.md
- packages/alova/typings/clienthook/hooks/tokenAuthentication.d.ts
- packages/alova/typings/clienthook/hooks/useFetcher.d.ts
- packages/alova/typings/clienthook/hooks/useSQRequest.d.ts
- packages/client/src/hooks/silent/silentQueue.ts
- packages/client/test/vue/useSQRequest.spec.ts
- packages/client/typings/clienthook/hooks/useSQRequest.d.ts
#434)
fix: cannot stop pushing SilentMethod into queue when using async handler in onBeforePushQueue(#434)
**文档 / Docs**
None
> fix: cannot stop pushing SilentMethod into queue when using async handler in onBeforePushQueue(#434)

- .changeset/spicy-moose-pull.md
- packages/alova/src/functions/sendRequest.ts
- packages/alova/test/browser/global/createAlova.spec.ts
- packages/alova/typings/index.d.ts
无
将`beforeRequest`中处理的最新请求参数进行请求
**文档 / Docs**
passed
> fix: use the newest params to request modified in `beforeRequest`

- .changeset/four-fishes-accept.md
- packages/client/src/hooks/core/implements/createRequestState.ts
[Issue ID]
none
uploading and downloading from usehooks do not update by calling send in react
**文档 / Docs**
all passed
> fix(react): uploading and downloading from usehooks do not update by calling send in react

- .changeset/proud-dolls-think.md
- packages/server/src/hooks/rateLimit.ts
- packages/server/test/rateLimit.spec.ts
close #462 
fix: decrease msBeforeNext value in real time when points exceed limit
**文档 / Docs**
when implement limiter by extending class `RateLimiterStoreAbstract`, the `expireTime` should not be updated in every `_upsert` action.
here's the key: If the old `expireTime` is later than now, just keep this value and do not update.
the value `msBeforeNext` is calculated by the last record written to the store, which contains `expireTime`. that's why this value will not reduce in previous version because it always update the expireTime.
> fix: `msBeforeNext` not reduce in server/rate-limit (#462)

- .changeset/metal-radios-clean.md
- packages/alova/typings/clienthook/general.d.ts
- packages/alova/typings/clienthook/hooks/updateState.d.ts
- packages/alova/typings/index.d.ts
- packages/client/src/hooks/core/implements/createHook.ts
- packages/client/src/hooks/core/implements/createRequestState.ts
- packages/client/src/hooks/core/implements/stateCache.ts
- packages/client/src/hooks/core/implements/useHookToSendRequest.ts
- packages/client/src/hooks/pagination/usePagination.ts
- packages/client/src/updateState.ts
- packages/client/test/react/core/update-state.spec.tsx
- packages/client/test/react/usePagination.spec.tsx
- packages/client/test/react/useRetriableRequest.spec.tsx
- packages/client/test/vue/core/functional/update-state.spec.ts
- packages/client/test/vue/usePagination.spec.ts
- packages/client/typings/clienthook/general.d.ts
- packages/client/typings/clienthook/hooks/updateState.d.ts
none
correct key `listData` to `data` in usePagination
**文档 / Docs**
all passed
> fix: correct key listData to data in usePagination

- .changeset/fifty-dancers-walk.md
- packages/alova/typings/clienthook/hooks/useForm.d.ts
- packages/client/typings/clienthook/hooks/useForm.d.ts
[Issue ID]
fix formData typof of `useForm`
**文档 / Docs**
all passed
> fix: fix formData typof of `useForm`

- .changeset/honest-lizards-grin.md
- README.md
- README.zh-CN.md
- internal/testUtils.ts
- packages/alova/typings/clienthook/general.d.ts
- packages/alova/typings/clienthook/hooks/useCaptcha.d.ts
- packages/alova/typings/clienthook/hooks/useForm.d.ts
- packages/alova/typings/clienthook/hooks/usePagination.d.ts
- packages/alova/typings/clienthook/hooks/useRetriable.d.ts
- packages/client/test/type/exposure.spec.ts
- packages/client/typings/clienthook/general.d.ts
- packages/client/typings/clienthook/hooks/useCaptcha.d.ts
- packages/client/typings/clienthook/hooks/useForm.d.ts
- packages/client/typings/clienthook/hooks/usePagination.d.ts
- packages/client/typings/clienthook/hooks/useRetriable.d.ts
fix the incorrect exposure type of the use hook. (`usePagination`, `useForm`, `useRetriable` etc...)
**文档 / Docs**
This issue is caused by incorrectly defining the return type of `this` in `UseHookExposure`. I added a generic context type called `SelfType` to make it possible to pass "this" through manually.
> fix: correct exposure type of usePagination

- .changeset/shiny-balloons-sit.md
- packages/alova/src/alova.ts
- packages/alova/test/browser/behavior/l1Cache.spec.ts
- packages/alova/test/browser/behavior/l2Cache.spec.ts
- packages/alova/test/browser/global/methodInstance.spec.ts
none
unified the request that the types contain request body to be `undefined`
all passed
> fix: unified the request that the types contain request body to be `undefined`

- .changeset/itchy-apricots-tan.md
- packages/alova/package.json
- packages/alova/typings/fetch.d.cts
- packages/alova/typings/fetch.d.ts
fix #539
**文档 / Docs**
all passed
> fix(alova/fetch): fix that cannot found alova/fetch in ts5.6

- .changeset/funny-meals-ring.md
- .changeset/loud-eggs-listen.md
- packages/alova/typings/clienthook/hooks/actionDelegationMiddleware.d.ts
- packages/alova/typings/clienthook/hooks/useAutoRequest.d.ts
- packages/alova/typings/clienthook/hooks/useCaptcha.d.ts
- packages/alova/typings/clienthook/hooks/useForm.d.ts
- packages/alova/typings/clienthook/hooks/usePagination.d.ts
- packages/alova/typings/clienthook/hooks/useRetriable.d.ts
- packages/alova/typings/clienthook/hooks/useSQRequest.d.ts
- packages/alova/typings/clienthook/hooks/useSerialRequest.d.ts
- packages/client/src/hooks/useAutoRequest.ts
- packages/client/src/hooks/useCaptcha.ts
- packages/client/src/hooks/useForm.ts
- packages/client/test/type/exposure.spec.ts
- packages/client/test/vue/useForm.spec.ts
- packages/client/tsconfig.json
- packages/client/typings/clienthook/hooks/actionDelegationMiddleware.d.ts
- packages/client/typings/clienthook/hooks/useAutoRequest.d.ts
- packages/client/typings/clienthook/hooks/useCaptcha.d.ts
- packages/client/typings/clienthook/hooks/useForm.d.ts
- packages/client/typings/clienthook/hooks/usePagination.d.ts
- packages/client/typings/clienthook/hooks/useRetriable.d.ts
- packages/client/typings/clienthook/hooks/useSQRequest.d.ts
- packages/client/typings/clienthook/hooks/useSerialRequest.d.ts
- packages/shared/src/model/FrameworkState.ts
fix:
- correct incorrect reference paths after `shared` package build
- correct type inconsistency between the form arg of handler and initialData in `useForm`
**文档 / Docs**
_none_
> fix: the type issue of `useForm` and `shared` package

- .changeset/five-dolls-add.md
- packages/alova/typings/clienthook/helper.d.ts
- packages/alova/typings/clienthook/index.d.ts
- packages/client/src/index.ts
- packages/client/typings/clienthook/helper.d.ts
- packages/client/typings/clienthook/index.d.ts
none
fix that missing export `statesHookHelper` from `alova/client`
**文档 / Docs**
https://alova.js.org/tutorial/advanced/custom/client-strategy#usehook
no need.
> fix: export `statesHookHelper` from `alova/client`

- .changeset/stupid-needles-play.md
- packages/client/src/hooks/core/implements/createRequestState.ts
- packages/client/test/react/core/useRequest.spec.tsx
- packages/client/test/vue/core/hooks/useRequest-http.spec.ts
close #594 
prevent screen flash when hit cache in use hooks
add tests
> fix: setting the cached data if found on useRequest initialization

- .changeset/good-actors-share.md
- packages/adapter-xhr/typings/index.d.ts
mark option type as optional.
**文档 / Docs**
*None*
> fix: mark option type as optional

- .changeset/swift-suits-wait.md
- internal/mockServer.ts
- internal/testUtils.ts
- packages/alova/src/functions/sendRequest.ts
- packages/alova/test/browser/behavior/l2Cache.spec.ts
#624 
fix: cannot force send request in restore cache mode
**文档 / Docs**
*None*
> fix: cannot force send request in restore cache mode

- .changeset/little-baboons-wave.md
- packages/client/src/hooks/pagination/usePagination.ts
- packages/client/test/react/usePagination.spec.tsx
- packages/client/test/vue/usePagination.spec.ts
none
fix that mismatching cache when items clear in last page
**文档 / Docs**
none
added and all passed
> fix: fix that mismatching cache when items clear in last page

- .changeset/famous-gorillas-act.md
- packages/adapter-axios/src/requestAdapter.ts
- packages/adapter-axios/test/browser/requestAdapter.spec.ts
> fix: Add optional chaining to headers returned by requestAdapter

- .changeset/ninety-eagles-dream.md
- packages/alova/src/functions/manipulateCache.ts
- packages/alova/test/server/cache.spec.ts
- packages/alova/typings/index.d.ts
[Issue ID]
remove the checking of l2 cache in memory mode when invalidate cache
all passed!
> fix: shouldn't check l2 cache in memory mode when invalidate cache

- .changeset/giant-maps-cheat.md
- packages/alova/src/alova.ts
- packages/alova/src/defaults/cacheAdapter.ts
- packages/alova/test/server/cache.spec.ts
- packages/alova/test/server/createAlova.spec.ts
- packages/alova/typings/serverhook.d.ts
none
fix that l2Cache is not defined in `invalidateCache`
all passed
> fix: fix that l2Cache is not defined in `invalidateCache`

- .changeset/angry-impalas-doubt.md
- packages/adapter-mock/src/defaults.ts
- packages/adapter-mock/test/mockRequest.spec.ts
fix that cannot receive headers default in mock adapter
all passed
> fix(adapter-mock): fix that cannot receive headers default in mock adapter

- .changeset/long-llamas-sell.md
- packages/alova/typings/clienthook/hooks/useSSE.d.ts
- packages/client/src/event.ts
- packages/client/src/hooks/useSSE.ts
- packages/client/test/react/useSSE.spec.tsx
- packages/client/test/type/exposure.spec-d.ts
- packages/client/test/vue/components/use-sse.vue
- packages/client/typings/clienthook/hooks/useSSE.d.ts
#670 
- fix the issue where the on method in useSSE cannot be chained
- remove method type `SSEOn`
- remove generic type `Data` to make the data type consistent with AG Responded
**文档 / Docs**
*None*
All tests have passed
> fix: `on` method in useSSE cannot be chained #670

- .changeset/lemon-waves-leave.md
- packages/alova/typings/clienthook/hooks/actionDelegationMiddleware.d.ts
- packages/client/test/type/actionDelegation.spec-d.ts
- packages/client/typings/clienthook/hooks/actionDelegationMiddleware.d.ts
- packages/client/vitest.config.ssr.ts
- vitest.config.base.ts
#673 
- correct type declaration of `accessAction()`
- update vitest config to ensure `*.spec-d.ts` tests runs correctly
**文档 / Docs**
*None*
All tests have passed.
> fix(types): correct type declaration of `accessAction()` #673
