alovajs/alova

- package.json
- src/Method.ts
- src/functions/manipulateCache.ts
- src/functions/sendRequest.ts
- src/functions/updateState.ts
- src/predefine/GlobalFetch.ts
- src/storage/methodSnapShots.ts
- src/utils/cloneMethod.ts
- src/utils/helper.ts
- test/browser/hooks/useRequest-otherData.spec.ts
- test/browser/stateManager/invalidate-cache.spec.ts
- typings/index.d.ts
- fix: method matches error when use reference value
- refactor: don't cache when request body is special data such as FormData, Blob, ArrayBuffer
> release: v2.0.5

- package.json
> fix: correct the compatibility of types definition in package.json #87

- jest.config.node.ts
- jest.config.ts
- src/index.ts
> fix: import.env not define problem

- jest.config.ts
- src/functions/createRequestState.ts
- src/predefine/ReactHook.ts
- test/browser/hooks/useRequest-http-vue.spec.ts
- test/browser/hooks/useRequest-react.spec.tsx
- test/browser/middleware/useRequest.spec.ts
- test/browser/stateManager/update-state-react.spec.tsx
- test/browser/stateManager/update-state-svelte.spec.ts
- test/browser/stateManager/update-state-vue.spec.ts
- test/components/svelte/page-useWatcher-immediate.svelte
- test/mockServer.ts
- typings/index.d.ts
> fix(abort): multiple times abort is work in react

- src/utils/variables.ts
> fix: fix that doesn't request in mini program

- src/functions/createRequestState.ts
- src/hooks/useWatcher.ts
- test/browser/hooks/react/useWatcher.spec.tsx
- test/browser/hooks/svelte/useWatcher.spec.ts
- test/browser/hooks/vue/useWatcher.spec.ts
- test/components/svelte/page-useWatcher-abortLast.svelte
- typings/index.d.ts
@JOU-amjs 作者你好，这是关于这个 issue 的代码 #136 ，麻烦你看一下😁
> fix: add abortLast for useWatcher

- README.zh-CN.md
- src/functions/sendRequest.ts
- test/browser/global/createAlova.spec.ts
- test/utils.ts
- typings/index.d.ts
> feat: add onComplete in global response interceptor

- README.md
- README.zh-CN.md
- typings/index.d.ts
- typings/vuehook.d.ts
> fix: type error of statesHook and caused the type inference error

- src/functions/useHookToSendRequest.ts
- test/browser/hooks/vue/useFetcher.spec.ts
- typings/index.d.ts
> feat: Add updateState configuration to useFetcher with default is true

- src/Method.ts
> fix: incorrect building of globalfetch cause not initialize error

- src/functions/createRequestState.ts
> fix: uploading state not working(#339)

- package.json
> fix(cjs): add the cjs bundle of vuehook, reacthook, sveltehook

- src/functions/sendRequest.ts
- test/browser/behavior/persist-response-vue.spec.ts
[Issue ID]
修复在placeholder模式下也会保存内存缓存的问题
**文档 / Docs**
无修改
已修改对应测试用例并通过
> fix: fix that saving memory cache in placeholder cache mode

- .npmrc
[Issue ID]
try to fix the publishing error, now test
**文档 / Docs**
> ci: fix error publishing with 404

- .changeset/olive-pens-sin.md
- packages/shared/package.json
> set version to 1.0.0

- .changeset/wild-ants-draw.md
- packages/adapter-axios/package.json
- packages/adapter-mock/package.json
- packages/adapter-taro/package.json
- packages/adapter-uniapp/package.json
- packages/adapter-xhr/package.json
- packages/alova/package.json
- packages/client/package.json
- packages/psc/package.json
- packages/server/package.json
- packages/vue-options/package.json
> chore: set packages version to x.0.0

- .changeset/config.json
- .changeset/cuddly-mice-double.md
- .changeset/shy-balloons-wash.md
- packages/alova/package.json
- packages/server/package.json
- packages/server/typings/index.d.ts
> chore: fix type declarations in alova

- README.md
- README.zh-CN.md
- packages/alova/README.md
- packages/alova/README.zh-CN.md
[Issue ID]
update the README.md
**文档 / Docs**
> docs: update README.md

- .changeset/lucky-wolves-agree.md
- .changeset/wise-timers-pull.md
- packages/alova/package.json
- packages/shared/src/vars.ts
> fix: cannot request in uniapp

- .changeset/perfect-mice-train.md
- .github/workflows/release-next.yml
- jest.config.base.ts
- packages/alova/typings/serverhook.d.ts
- packages/client/src/hooks/useForm.ts
- packages/shared/src/vars.ts
[Issue ID]
修复isTesting导致的`global is not defined`报错
**文档 / Docs**
> fix: remove the variable `isTesting`

- .github/workflows/release-next.yml
> ci: reset setupGitUser column

- .changeset/spotty-pugs-punch.md
- packages/client/src/hooks/core/implements/createRequestState.ts
- packages/client/test/react/core/useWatcher.spec.tsx
#421
fix debounce not working in useWatcher
> fix: debounce not working in useWatcher

- .changeset/breezy-dolls-glow.md
- packages/shared/src/function.ts
#423 
fix: computed does not work when its dependent exported value is not used
> fix: computed does not work when its dependent exported value is not used (#423)

- README.md
- README.zh-CN.md
- examples/react/package.json
- examples/server/index.ts
- examples/server/package.json
- examples/server/server.ts
- examples/svelte/package.json
- examples/vue/package.json
- pnpm-lock.yaml
> chore: update examples deps

- .changeset/strange-needles-cry.md
- packages/alova/typings/stateshook/react.d.ts
- packages/client/src/statesHook/react.ts
- packages/client/typings/clienthook/hooks/useForm.d.ts
- packages/client/typings/stateshook/react.d.ts
[Issue ID]
close #492
modify the `react.ts` and compatible with preact when using react
**文档 / Docs**
all passed
> fix: compatible with preact when using react

- .changeset/nine-wombats-marry.md
- packages/alova/package.json
- packages/alova/typings/stateshook/vue-demi.d.ts
- packages/client/jest.config.ts
- packages/client/test/vue-demi/useFetcher.spec.ts
- packages/client/test/vue-demi/useRequest-http.spec.ts
- packages/client/test/vue-demi/useWatcher.spec.ts
[Issue ID]
无
fix that statesHook vue-demi is not found
**文档 / Docs**
all passed
> fix(vue-demi): fix that statesHook vue-demi is not found

- .changeset/twelve-lions-compare.md
- internal/mockServer.ts
- packages/adapter-xhr/src/requestAdapter.ts
- packages/adapter-xhr/test/requestAdapter.spec.ts
close #501 
fix: prevent null response for text type
> fix: prevent null response for text type #501

- .changeset/quiet-tigers-rhyme.md
- examples/server/routes/rateLimit.ts
- examples/server/views/rateLimit.html
- packages/client/src/hooks/pagination/usePagination.ts
- packages/client/src/hooks/useCaptcha.ts
- packages/client/test/vue/usePagination.spec.ts
- pnpm-lock.yaml
[Issue ID]
close #510
To be effective for `usePagination` when calling `updateState`
**文档 / Docs**
all passed
> fix(client): to be effective for `usePagination` when calling `updateState`

- .changeset/tasty-ravens-shave.md
- packages/shared/package.json
- pnpm-lock.yaml
close #523
fix: cannot import types from `@alova/shared` in the build
> fix: cannot import types from `@alova/shared` in the build (close #523)

- .changeset/nine-coats-complain.md
- packages/alova/package.json
- packages/alova/tsconfig.json
> fix: publish fetch.d.cts

- .github/workflows/release.yml
- .releaserc.yml
- package.json
- tsconfig.json
- typings/globalfetch.d.cts
- typings/globalfetch.d.ts
fix that typo of alova/globalfetch in ts5.6
> fix: fix that typo of alova/globalfetch in ts5.6

- .changeset/blue-otters-doubt.md
- packages/client/src/hooks/core/implements/createRequestState.ts
- packages/shared/typings/alova-shared.d.ts
close #580
#580 
fix: fix that debounce not effect in react
> fix: fix that debounce not effect in react

- .changeset/cuddly-cherries-approve.md
- packages/client/src/hooks/pagination/usePagination.ts
- packages/client/test/vue/usePagination.spec.ts
fix: allow middleware to interrupt requests in `usePagination`
**文档 / Docs**
*NONE*
> fix: allow middleware to interrupt requests in `usePagination`

- .changeset/fluffy-ducks-shop.md
- packages/alova/typings/clienthook/hooks/usePagination.d.ts
- packages/client/test/type/sendArgs.spec-d.ts
- packages/client/typings/clienthook/hooks/usePagination.d.ts
fix type error, remove `page` and `pageSize` parameters from usePagination's send function.
**文档 / Docs**
*NONE*
> fix: remove `page` and `pageSize` parameters from usePagination's send function

- .changeset/silent-tips-chew.md
- packages/adapter-xhr/src/requestAdapter.ts
- packages/adapter-xhr/test/requestAdapter.spec.ts
- packages/adapter-xhr/typings/index.d.ts
none
adapter-xhr: export xhr instance in `options.create` of adapter
**文档 / Docs**
added to docs
all passed
> feat(adapter-xhr): export xhr instance in `options.create` of adapter

- .changeset/young-moose-check.md
- packages/adapter-mock/src/MockRequest.ts
- packages/adapter-mock/test/mockRequest.spec.ts
- packages/adapter-mock/typings/index.d.ts
无
修复了使用mock时 `POST` 请时 `data` 传参为 `string` 类型无法处理的问题
**文档 / Docs**
无
通过
> fix(mock): 修复post请求data为字符串时处理异常的问题

- .changeset/giant-dragons-relate.md
- packages/alova/typings/index.d.ts
- packages/client/src/hooks/core/implements/createHook.ts
- packages/client/src/hooks/core/implements/createRequestState.ts
- packages/client/src/hooks/core/implements/stateCache.ts
- packages/client/src/hooks/core/implements/useHookToSendRequest.ts
- packages/client/src/statesHook/react.ts
- packages/client/src/updateState.ts
- packages/client/test/react/actionDelegationMiddleware.spec.tsx
- packages/client/test/react/core/update-state.spec.tsx
- packages/client/test/react/core/useRequest.spec.tsx
- packages/client/test/react/useAutoRequest.spec.tsx
- packages/client/test/solid/statesHook.solid.spec.tsx
- packages/client/test/svelte/core/update-state.spec.ts
- packages/client/test/vue/core/functional/update-state.spec.ts
- packages/client/typings/clienthook/general.d.ts
close #357
fix that cannot update state which is the same key but distribute in different component
all passed
> fix: fix that cannot update state which is the same key but distribute in different component

- .changeset/long-lobsters-wonder.md
> chore: release redis storage adapter

- .changeset/plenty-countries-tickle.md
- packages/alova/typings/index.d.ts
> feat: update the MethodType type to support string extension

- .changeset/smart-pugs-kiss.md
- packages/alova/typings/index.d.ts
*None*
fix typo in d.ts
**文档 / Docs**
*None*
> fix: typo in d.ts
